AWSTemplateFormatVersion: 2010-09-09
Resources:
  MICCAUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
        InviteMessageTemplate:
          EmailSubject: MICCA IPLARC Reporting Login Information
          EmailMessage: |
            Hello, 
             
            You have been designated as a user of the MICCA project.  
            Please use this link to login to the MICCA website (https://larc.micca.report/) 
            
            The first time you access the site you will be asked to reset your password.
            Your user name is {username}
            Your temporary password is {####}

      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          TemporaryPasswordValidityDays: 7
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
          MinimumLength: 8
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: false
        DeviceOnlyRememberedOnUserPrompt: true
      EmailVerificationMessage: 'Email verification code for MICCA IPLARC reporting {####}'
      EmailVerificationSubject: Verification for MICCA IPLARC
      MfaConfiguration: 'OFF'
      Schema:
        - Name: email
          Mutable: false
          Required: true
        - Name: site
          Mutable: true
          Required: false
          AttributeDataType: String
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: true
      UserPoolName: micca-users
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailMessageByLink: >-
          Use the following link to confirm your email for MICCA IPLARC {##confirm##}
  DisplayLabUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: "Display lab users and administrators"
      GroupName: DisplayLabUsers
      Precedence: 0
      UserPoolId: !Ref MICCAUserPool
