AWSTemplateFormatVersion: 2010-09-09
Resources:
  MICCAUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
        InviteMessageTemplate:
          EmailSubject: MICCA IPLARC Reporting Login Information
          EmailMessage: >-
            You have been designated as a user of the MICCA project. {username}
            {####}
        UnusedAccountValidityDays: 60
      AutoVerifiedAttributes:
        - email
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: false
        DeviceOnlyRememberedOnUserPrompt: true
      EmailVerificationMessage: 'Email verification code for MICCA IPLARC reporting {####}'
      EmailVerificationSubject: Verification for MICCA IPLARC
      MfaConfiguration: 'OFF'
      Schema:
        - Name: email
          Mutable: false
          Required: true
        - Name: site
          Mutable: true
          Required: false
          AttributeDataType: String
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: true
      UserPoolName: micca-users
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailMessageByLink: >-
          Use the following link to confirm your email for MICCA IPLARC {##confirm##}
  DisplayLabUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: "Display lab users and administrators"
      GroupName: DisplayLabUsers
      Precedence: 0
      UserPoolId: !Ref MICCAUserPool
