source 'https://rubygems.org'

gem 'sinatra'
gem 'json'
gem 'rack'
gem 'rack-contrib'
gem 'aws-record'
gem 'rake'
gem 'rubysl-base64'
gem 'omniauth-cognito-idp', '~> 0.1.1'

# These are the dependencies that are used only for unit tests.
group :test do
  gem "rspec"
  gem "rack-test"
  gem "pry"
end

# Dependencies provided by container need to be installed locally
group :local do
  gem "aws-sdk-cognitoidentityprovider"
  gem "aws-sdk-s3"
  gem "aws-record"
end
